on:
  push:

jobs:
  pull:
    strategy:      
      matrix:
        number: [0, 1, 2, 3, 4, 5, 6, 7, 8]
        include:
          - domain-name: docker.pkg.github.com
          - image-name: docker-errors
          - tag-name: latest
          - source-image: alpine:latest
          - github-repository: ${{ github.repository }}
          - token: $GITHUB_TOKEN
          - number: 0
            job-name: success
          - number: 1
            job-name: unknown tag
            tag-name: unknown
          - number: 2
            job-name: unknown image
            image-name: unknown
          - number: 3
            job-name: upper-case image name
            image-name: DOCKER-ERRORS
          - number: 4
            job-name: no access private repo
            github-repository: github/github
          - number: 5
            job-name: no scope token
            token: "2a78e44b221e182c6e1e24fe9aec7e76f122391b" # no-scope token
          - number: 6
            job-name: read packages token
            token: ${{ format('{0}{1}', '11f80c8d98105405a3c', '94c737be9ddeedf806e52') }} # read:packages
          - number: 7
            job-name: bad token
            token: bad-token
          - number: 8
            job-name: missing image name
            github-repository: ${{ github.repository_owner }}
            image-name: docker-errors
      fail-fast: false
    name: ${{ matrix.job-name }}
    runs-on: ubuntu-latest

    env:
      image: ${{ matrix.domain-name }}/${{ matrix.github-repository }}/${{ matrix.image-name }}:${{ matrix.tag-name }}
      GITHUB_TOKEN: ${{ github.token }}

    steps:
    - run: docker login https://docker.pkg.github.com -u token --password-stdin <<< ${{ matrix.token }}
    - run: docker pull ${{ env.image }}
