on:
  push:

jobs:
  publish:
    strategy:      
      matrix:
        number: [0]
        include:
          - image-name: docker-errors
          - tag-name: latest
          - source-image: alpine:latest
      fail-fast: false

    runs-on: ubuntu-latest

    env:
      image: docker.pkg.github.com/${{ github.repository }}/${{ matrix.image-name }}:${{ matrix.tag-name }}

    steps:
    - run: docker pull ${{ matrix.source-image }}
    - run: docker tag ${{ matrix.source-image }} ${{ matrix.image }}
    - run: docker login https://docker.pkg.github.com -u token -p ${{ github.token }}
    - run: docker push ${{ matrix.image }}
