on:
  push:

jobs:
  push:
    strategy:      
      matrix:
        domain-name: [ghcr.io, docker.pkg.github.com]
        number: [0, 1, 2, 3, 4, 5, 6, 7, 8]
        include:
          - image-name: docker-errors
          - tag-name: latest
          - source-image: alpine:latest
          - github-repository: ${{ github.repository }}
          - token: $PACKAGES_TOKEN
          - number: 0
            job-name: success
          - number: 1
            job-name: existing image name
            image-name: image
          - number: 2
            job-name: upper-case image name
            image-name: DOCKER-ERRORS-UPPER-CASE
          - number: 3
            job-name: trailing dash
            image-name: docker-errors-
          - number: 4
            job-name: wrong repo
            github-repository: desktop/desktop
          - number: 5
            job-name: no scope token
            token: "2a78e44b221e182c6e1e24fe9aec7e76f122391b" # no-scope token
          - number: 6
            job-name: read packages token
            token: ${{ format('{0}{1}', '11f80c8d98105405a3c', '94c737be9ddeedf806e52') }} # read:packages
          - number: 7
            job-name: bad token
            token: bad-token
          - number: 8
            job-name: missing image name
            github-repository: ${{ github.repository_owner }}
            image-name: docker-errors
          - number: 9
            job-name: publish-to-org
            github-repository: mutantdesign/docker-errors
      fail-fast: false
    name: ${{ matrix.domain-name }}-${{ matrix.job-name }}
    runs-on: ubuntu-latest

    env:
      image: ${{ matrix.domain-name }}/${{ matrix.github-repository }}/${{ matrix.image-name }}:${{ matrix.tag-name }}
      PACKAGES_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

    steps:
    - run: docker pull ${{ matrix.source-image }}
    - run: docker tag ${{ matrix.source-image }} ${{ env.image }}
    - run: docker login https://${{ matrix.domain-name }} -u token --password-stdin <<< ${{ matrix.token }}
    - run: docker push ${{ env.image }}
