on:
  push:

jobs:
  publish:
    strategy:      
      matrix:
        number: [0, 1]
        include:
          - image-name: docker-errors
          - tag-name: latest
          - source-image: alpine:latest
          - number: 0
            job-name: success
          - number: 1
            job-name: existing image name
            image-name: image
          - number: 2
            job-name: upper-case image name
            image-name: DOCKER-ERRORS-UPPER-CASE
      fail-fast: false
    name: ${{ matrix.job-name }}
    runs-on: ubuntu-latest

    env:
      image: docker.pkg.github.com/${{ github.repository }}/${{ matrix.image-name }}:${{ matrix.tag-name }}

    steps:
    - run: docker pull ${{ matrix.source-image }}
    - run: docker tag ${{ matrix.source-image }} ${{ env.image }}
    - run: docker login https://docker.pkg.github.com -u token -p ${{ github.token }}
    - run: docker push ${{ env.image }}
