on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: docker login https://docker.pkg.github.com -u token --password-stdin <<< ${{ github.token }}
      - run: docker pull docker.pkg.github.com/jcansdale-test/docker-errors/docker-errors:latest
